name: Deploy to GitHub Pages (Subfolder)

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.x'  
          channel: 'stable'  

      - name: Change directory to Flutter project
        run: cd front_end/twwhdr_leaderborad

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web app
        run: flutter build web --base-href "/TWWHDR-Leaderboard/"

      - name: List contents of build/web
        run: ls -la ./build/web 

      - name: Deploy to GitHub Pages (Subfolder)
        uses: peaceiris/actions-gh-pages@v3  
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./build/web  
          force_orphan: true 
          user_name: 'github-ci[bot]' 
          user_email: 'github-actions[bot]@users.noreply.github.com'  
          commit_message: 'Deploy Flutter Web app to GitHub Pages (Subfolder)'  
